=== 2020/March 4,  YEY Report

Here comes a task/estimation report for YEY before going online and a number of questions/recommendations:

.Questions:
1. My Travel Destinations::
*** Do we send separate emails per destination? assuming a user have multiple travel destinations provided
*** Do we still send recommendations for the original destination?
2. Price Drop Alerts
*** How often prices are updated?
*** How often would you like price changes to be checked?
*** How scrapers are scheduled to run? Separately? Together? In general how do data flow into **yey_events** table in terms of time?

We can run price drop alert on each scraper run(?), I’m not sure, we need to answer those questions first.

.An issue on the web page
  When a new potential user (not signed in) tries to choose a region and clicks on Get a Price Alert, a page responds with error - Please choose a region and at least one category, which is a bug.

.Database
  We need a separate database for development purposes, completely independent from production one.

.Table Task/Time estimation
|===

| Order | Task | Time (h) | Buffer (h)

| 1
| Deduplication
| 16
| 4

| 2
| My Travel Destinations
| 18
| 6

| 3
| Limitation - analysis
| 10
| 3

| 4
| Price Drop Alerts - analysis
| 0
| 0

| 
| Sum
| 44
|

|===

.Estimation comments:
** 1: deduplication module development and integration into recommender engine.
** 3: Limit a number of the same events being sent to the same user - at first we need to dig into data and do the analysis, then I’ll know how much time will implementation take.
** 4: Price Drop Alerts - further research and information exchange required.
